# Settings for the app
app:
  # HTML Title
  title: Dude Where's My Bike?
  # Header name
  name: DUDE WHERE'S MY BIKE?
  # Meta description that will show up in Google search results
  meta_description: _(A map to share user-reported locations of bike thefts in Miami, Florida)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 25.95
      lng: -80.2984
    zoom: 10
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: 'Developed by <a href="Code for Miami, " target="_blank">Code for Miami</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  theft: 
    default: blue-dot
    focused: blue-pin
    label: _(theft)

  # landmark:
  #   default: blue
  #   focused: red
  #   label: _(theft)
  # park:
  #   default: blue
  #   focused: red
  #   label: _(Park)
  # school:
  #   default: blue
  #   focused: red
  #   label: _(School)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue-dot:
    iconUrl: /static/css/images/markers/dot-0d85e9.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  blue-pin:
    iconUrl: /static/css/images/markers/marker-0d85e9.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Report a theft)
  action_text: _(reported)
  title: _(Report a stolen bike)
  action_text: _(reported)
  anonymous_name: _(Someone)
  submit_button_label: _(Report)
  items:
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(Theft)
          value: theft
        - label: _(Landmark)
          value: landmark
      name: location_type
    - prompt: _(Where did it happen?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Address, intersection, or other geographical description)
        - key: size
          value: 30
      name: name
    - prompt: _(Your name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(First, last)
        - key: size
          value: 30
    - prompt : _(Your email)
      type: text
      name: submitter_email
      optional: true
      attrs:
         - key: placeholder
           value: _(No one sees it, just us.)
         - key: size
           value: 30
    - prompt: _(Got a photo?)
      inputfile_label: _(Add a photo)
      type: file
      name: image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Anything else you can tell us?)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(e.g. What make, model, color was it, when was it last seen, what you were doing before it happened, best way to contact you)

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: false

  - title: _(The Miami Bike Scene)
    external: true
    url: http://www.themiamibikescene.com/